language: python
python:
    - "3.7"
env:
install: 
    - pip install poetry
    - poetry install
script: poetry run make html SPHINXOPTS="-W -n"
notifications:
    email:
        - james@openstates.org
