[tool.poetry]
name = "openstates-documentation"
version = "2019.12"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
sphinx = "^2.2"
sphinx_rtd_theme = "^0.4.3"
mkdocs-material = "^8.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
