name: Lint Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: pip install sphinx sphinx_rtd_theme
    - name: sphinx build check
      run: make html SPHINXOPTS="-W -n"
